### ISSUE TITLE
Strange if

### ISSUE THREAD

**Issue by oliverpool** [jadr2ddude/sse#1]
Hi,

I've seen your repo on the #reviews channel on gophers.slack.com.
I've needed such SSE event sender in go and was interested to know how you implemented it!

I've seen the following condition in `sender.go` (https://github.com/jadr2ddude/sse/blob/master/sender.go#L110)
```
if name == "data" && strings.ContainsAny(name, "\n\r") {
```
How can the `name` be equal to `"data"` **and** contain `"\n\r"`?

---

Are you interested (if I find some time) for a further review of your code? (and maybe some PRs ?)

**Comment by niaow** [comment]
Thanks for reviewing my code! I believe that I meant to use val instead of name. I will fix this when I get a chance. A further review would be great!

**Comment by niaow** [comment]
Fixed in commit 633e995
