### ISSUE TITLE
Choice of standard

### ISSUE THREAD

**Issue by oliverpool** [jadr2ddude/sse#4]
In your code, you refer to the following standard: https://www.w3.org/TR/2009/WD-eventsource-20090421/#event-stream-interpretations

Any reason, why you didn't choose some later version? (like https://www.w3.org/TR/2015/REC-eventsource-20150203/ - which recommends https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events)

**Comment by niaow** [comment]
These all work the same so I would be willing to accept a PR changing the URLs. I don't really see too much of a difference.

**Comment by oliverpool** [comment]
Choosing the last standard: https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events

Set in f830e594eaf15aae815741815b7ef7b9c5e76cc8
