### ISSUE TITLE
Distinguish EOF from unexpected EOF

### ISSUE THREAD

**Issue by niaow** [jadr2ddude/sse#5]
Right now Client.Event returns an io.ErrUnexpectedEOF. This should be changed to io.EOF when nothing is read at all.

**Comment by oliverpool** [comment]
Is there no such thing as `UnexpectedEOF`?

According to the [standard](https://html.spec.whatwg.org/multipage/server-sent-events.html#dispatchMessage):
> Once the end of the file is reached, any pending data must be discarded. (If the file ends in the middle of an event, before the final empty line, the incomplete event is not dispatched.)

Then it can simply be `EOF` (and no need for `UnexpectedEOF`)

I think an `EOF` will always be unexpected and the client should always reconnect:
> Clients will reconnect if the connection is closed; a client can be told to stop reconnecting using the HTTP 204 No Content response code.

**Comment by niaow** [comment]
Ok. I was trying to keep this simple and wasnt indending to do reconnects, but I guess we can do reconnects.
